language: python
python:
  - "3.8"

cache:
  directories:
    - "~/.platformio"

env:
  - PLATFORMIO_CI_SRC=examples/R_Click/R_Click.ino

install:
  - pip install -U platformio

script:
  - platformio ci --lib="." --project-conf=platformio.ini